name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  
jobs:
  assign_high_priority:
    name: Add pull request to project 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/users/mvdebolskiy/projects/1
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          labeled: bug

