name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

env: 
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
jobs:
  assign_high_priority:
    runs-on: ubuntu-latest
    name: Assign to High Priority project
    steps:
    - name: Assign issues and pull requests with priority-high label to project 25
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/users/mvdebolskiy/projects/1'

